kr0ner/OneESP32ToRuleThemAll

- yaml/thz504.yaml
Agreed to make the changes stepwise and bring it back to thz504.yaml. 
First step I would need is to make the hardcoded pins variable to test the changes in my setup.
> added input variables for pins, humidity, and temp values

- src/communication.h
- yaml/wp_base.yaml
As proposed by @croessi https://github.com/kr0ner/OneESP32ToRuleThemAll/pull/24
> Calculate read/write ids based on CAN id

- esp32-poe-technik.yaml
- src/property.h
- yaml/common.yaml
- yaml/thz404.yaml
- yaml/thz504.yaml
- yaml/thz5_5_eco.yaml
- yaml/ttf07.yaml
- yaml/wp_base.yaml
TTF07 does not have a ventilation system and since it relies on geothermal energy, also has no compressor. Move the heatpump specific stuff out so that the remaining common part can be included by all variants.
Fixes #44
> Rename wp_base to common and move heatpump specific stuff to wp_base

- README.md
- esp32-poe-technik.yaml
- src/communication.h
- src/property.h
- src/simple_variant.h
- yaml/common.yaml
- yaml/energymeter.yaml
- yaml/wp_base.yaml
> Restructure repo to allow easier setup

- src/property.h
- yaml/ttf07.yaml
> Support more sensors for TTF07

- src/callback_handler.h
- yaml/wp_base.yaml
- yaml/wp_ventilation.yaml
> Adds power sensors for fan and el. heating

- yaml/wp_ventilation.yaml
closes: https://github.com/kr0ner/OneESP32ToRuleThemAll/issues/73
> Restore fan mode after reset

- yaml/ttf07.yaml
after setting new values, the heatpump switches within 2 seconds
> Implement PROGAMMSCHALTER for TTF07c

- yaml/common.yaml
@mkaiser as suggested in your comments
> Avoid peaks when calculating COP values

- src/property.h
- yaml/common.yaml
> Rename FEUCHTE to RAUMFEUCHTE

- yaml/common.yaml
- yaml/wp_base.yaml
> Move some sensors from common.yaml to wp_base.yaml

- src/simple_variant.h
Fixes: https://github.com/kr0ner/OneESP32ToRuleThemAll/issues/125
> Add missing header for chrono

- src/property.h
- yaml/wpl13.yaml
Resolves: #102
Resolves: #103
Resolves: #104
> Wpl13 improvements

- components/custom/__init__.py
- components/custom/climate/__init__.py
- components/custom/climate/custom_climate.h
- components/custom_component/__init__.py
- components/custom_component/custom_component.h
- yaml/energymeter.yaml
- yaml/wp_base.yaml
> Bring back custom components

- esp32-poe-technik.yaml
- yaml/wpl13.yaml
This reverts commit fd42b9b59630d634cd5325d6e0a17615dab9da01.
> Revert "break the build to highlight breaking changes"

- src/property.h
- yaml/wpl13.yaml
https://github.com/kr0ner/OneESP32ToRuleThemAll/issues/106
> fix volumenstrom #106

- yaml/wpl13.yaml
https://github.com/kr0ner/OneESP32ToRuleThemAll/issues/109
> address #109

- src/property.h
- yaml/wpl13.yaml
https://github.com/kr0ner/OneESP32ToRuleThemAll/issues/101
> Wpl13 - WPE-I HK: fix soll temp for hk1 and hk2

- src/property.h
- yaml/wpl13.yaml
https://github.com/kr0ner/OneESP32ToRuleThemAll/issues/116
> address #116

- src/property.h
- yaml/wp_temperature.yaml
- yaml/wpl13.yaml
https://github.com/kr0ner/OneESP32ToRuleThemAll/issues/112
> address #112

- src/property.h
- src/type.cpp
- yaml/sensors.yaml
- yaml/watermeter.yaml
- yaml/wp_base.yaml
- yaml/wp_generic.yaml
- yaml/wp_switch.yaml
- yaml/wpl13.yaml
Closes: #115 
Closes: #101 
Closes: #114 
Closes: #113 
Closes: #111 
Closes: #110 
Closes: #108
> Add changes from @adrai

- src/communication.h
Previously this was done by looking up the the ids of the existing CanMembers, which might lead to problems when an FEK is connected, because that one uses 0x1c01 instead of 0x8001 to request data from 0x601. Both are valid, but the code only handled 0x8001 correctly.
Fixes: #100, #188
> Directly obtain message type from read/write/response id
